{"teamList":[
{"name":"team1",
"groupId":"1",
"leader":"false",
"memberCnt":"3",
"mems":[
{"name":"aaa","mail":"aaa@aaa"},
{"name":"bbb","mail":"bbb@bbb"},
{"name":"ccc","mail":"ccc@ccc"}]
},
{"name":"team2",
"groupId":"2",
"leader":"true",
"memberCnt":"3",
"mems":[
{"name":"aaa","mail":"aaa@aaa"},
{"name":"bbb","mail":"bbb@bbb"},
{"name":"ccc","mail":"ccc@ccc"}]
}
]}