{"teamList":[
{"name":"team1",
"groupId":"1",
"leaderFlag":"false",
"leader":"aaa",
"memberCnt":"3",
"mems":[
{"name":"aaa","mail":"aaa@aaa","userId":"1"},
{"name":"bbb","mail":"bbb@bbb","userId":"2"},
{"name":"ccc","mail":"ccc@ccc","userId":"3"}]
},
{"name":"team2",
"groupId":"2",
"leaderFlag":"true",
"leader":"bbb",
"memberCnt":"3",
"mems":[
{"name":"aaa","mail":"aaa@aaa","userId":"4"},
{"name":"bbb","mail":"bbb@bbb","userId":"5"},
{"name":"ccc","mail":"ccc@ccc","userId":"6"}]
}
]}