{"teamList":[
{"name":"team1",
"groupId":"1",
"leaderFlag":"false",
"leader":"aaa",
"memberCnt":"3",
"mems":[
{"name":"aaa","mail":"aaa@aaa"},
{"name":"bbb","mail":"bbb@bbb"},
{"name":"ccc","mail":"ccc@ccc"}]
},
{"name":"team2",
"groupId":"2",
"leaderFlag":"true",
"leader":"bbb",
"memberCnt":"3",
"mems":[
{"name":"aaa","mail":"aaa@aaa"},
{"name":"bbb","mail":"bbb@bbb"},
{"name":"ccc","mail":"ccc@ccc"}]
}
]}